Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'class_methods'
    - 'included'
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

# Pending cops
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
